import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { clinicInfo, mapsURL, navLinks } from '../../data/clinic';
import { createWhatsAppURL } from '../../utils/whatsapp';
import { Brand, Button, ExternalLink, Icon } from '../common/UI';
import { FaWhatsapp } from 'react-icons/fa6';
export function Header() {
  const [open,setOpen] = useState(false); const [scrolled,setScrolled] = useState(false); const location=useLocation(); const menuButton=useRef();
  useEffect(()=>{setOpen(false);},[location.pathname]);
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>20);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll);},[]);
  useEffect(()=>{if(!open)return;const onKey=e=>{if(e.key==='Escape'){setOpen(false);menuButton.current?.focus();}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey);},[open]);
  return <><a className="skip-link" href="#main">Skip to content</a><div className="topbar"><div className="container topbar-inner"><span><span className="status-dot"/>24/7 Emergency Service</span><div>{clinicInfo.phones.map((p,i)=><a href={`tel:${p}`} key={p}>{i===0&&<Icon name="Phone" size={13}/>}<span>{p}</span></a>)}<span className="top-location"><Icon name="MapPin" size={13}/>{clinicInfo.address.replace(', Bihar','')}</span></div></div></div><header className={`header ${scrolled?'is-scrolled':''}`}><div className="container nav-inner"><Brand/><nav aria-label="Main navigation">{navLinks.map(([label,path])=><NavLink to={path} end key={path}>{label}</NavLink>)}</nav><Button className="nav-cta" to="/appointment"><Icon name="CalendarDays" size={16}/>Book Appointment</Button><button ref={menuButton} className="menu-toggle" aria-expanded={open} aria-controls="mobile-navigation" aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}><Icon name={open?'X':'Menu'}/></button></div>{open&&<nav id="mobile-navigation" className="mobile-navigation container" aria-label="Mobile navigation">{[...navLinks,['Book Appointment','/appointment']].map(([label,path])=><NavLink to={path} end key={path}>{label}<Icon name="ArrowUpRight" size={16}/></NavLink>)}</nav>}</header></>;
}
export function Footer() { return <footer className="footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><Brand/><p>{clinicInfo.tagline}.<br/>Compassionate care for our community.</p><div className="footer-social"><ExternalLink href={createWhatsAppURL()} aria-label="Contact clinic on WhatsApp"><FaWhatsapp size={20} aria-hidden="true"/></ExternalLink><a href={`tel:${clinicInfo.phones[0]}`} aria-label="Call clinic"><Icon name="Phone" size={19}/></a></div></div><div className="footer-links-group"><div><h3>Explore</h3>{[...navLinks,['Appointment','/appointment']].map(([n,p])=><Link key={p} to={p}>{n}</Link>)}</div><div><h3>Services</h3>{['General Physician','General Surgery','Women’s Health','Physiotherapy','Pathology','Emergency'].map(n=><Link to="/services" key={n}>{n}</Link>)}</div></div><div className="footer-contact-panel"><span className="footer-panel-label">GET IN TOUCH</span><h3>Care is one call away.</h3>{clinicInfo.phones.map(p=><a className="footer-contact" href={`tel:${p}`} key={p}><Icon name="Phone" size={15}/>{p}</a>)}<ExternalLink className="footer-contact footer-address" href={mapsURL}><Icon name="MapPin" size={17}/><span>Near Bazaar Samiti,<br/>Sitamarhi Road, Pupri, Bihar</span></ExternalLink><span className="footer-hindi" lang="hi">{clinicInfo.hindiAddress}</span></div></div><div className="footer-meta"><p className="disclaimer">Website information is for general informational purposes. For medical advice, diagnosis or treatment, consult a qualified healthcare professional.</p><div className="footer-bottom"><span>© {new Date().getFullYear()} {clinicInfo.name}. All Rights Reserved.</span><Link to="/privacy-policy">Privacy Policy</Link></div></div><ExternalLink className="developer-credit" href="https://mdmashoodalam.netlify.app/"><span>Designed &amp; Developed by</span><strong>Md Mashood Alam</strong><Icon name="ArrowUpRight" size={16}/></ExternalLink></div></footer>; }
export function FloatingActions() { const [show,setShow]=useState(false);useEffect(()=>{const update=()=>setShow(window.scrollY>600);window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);return <div className="floating-actions">{show&&<button className="back-top" aria-label="Scroll to top" onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><Icon name="ArrowUp"/></button>}<ExternalLink className="whatsapp-float" href={createWhatsAppURL()} aria-label="Chat with Hayat Health Care Clinic on WhatsApp"><FaWhatsapp size={29} aria-hidden="true"/><span className="whatsapp-tooltip">Chat on WhatsApp</span></ExternalLink></div>; }
