import { Link } from 'react-router-dom';
import { Button, DoctorPhoto, ExternalLink, Icon, Reveal, SectionTitle } from '../common/UI';
import { ServiceCard, DoctorCard } from '../common/Cards';
import { services, facilities } from '../../data/services';
import { doctors } from '../../data/doctors';
import { clinicInfo, mapsURL, mapQuery } from '../../data/clinic';
import { faqs } from '../../data/faqs';
import { createWhatsAppURL } from '../../utils/whatsapp';
export function AboutPreview({ full = false }) { return <section className="section container about-section"><div className="about-panel"><div className="about-mark"><Icon name="HeartHandshake" size={50}/></div><span className="eyebrow">TRUST. CARE. HEALING.</span><h2>A community<br/>you can trust.</h2><p>Care that listens.<br/>Support that stays with you.</p><div className="about-local"><Icon name="MapPin" size={18}/><span>Rooted in Pupri.<br/><strong>Here for your family.</strong></span></div></div><div className="about-copy"><span className="eyebrow">CARE CLOSE TO HOME</span><h2>Caring for your<br/>family’s health.</h2><p>At Hayat Health Care Clinic, we believe good healthcare begins with listening. We aim to make dependable, patient-focused care accessible to individuals and families in Pupri and the surrounding communities.</p><div className="about-features">{[['HeartHandshake','Patient First Care'],['Stethoscope','Experienced Doctors'],['HeartPulse','Emergency Support'],['Hospital','Essential Facilities']].map(([i,n])=><span key={n}><Icon name={i} size={19}/>{n}</span>)}</div>{full?<p className="director-line">Director · <strong>{clinicInfo.director}</strong></p>:<Link className="text-link" to="/about">Get to know our clinic<Icon name="ArrowUpRight" size={17}/></Link>}<div className="trust-stats"><div><strong>24/7</strong><span>Emergency support</span></div><div><strong>Multiple</strong><span>Healthcare services</span></div><div><strong>Trusted</strong><span>Local care</span></div></div></div></section>; }
export function ServicesPreview(){return <section className="section pale-section"><div className="container"><SectionTitle eyebrow="HERE FOR EVERYDAY HEALTH" title="Our medical services" link="/services" linkText="Explore all services"/><Reveal className="services-grid">{services.slice(0,8).map(s=><ServiceCard key={s.id} service={s}/>)}</Reveal></div></section>;}
export function FacilitiesSection({ full=false }){return <section className={`section facilities-section ${full?'facilities-full':''}`}><div className="container"><SectionTitle eyebrow="ESSENTIAL CARE, UNDER ONE ROOF" title="Facilities available" link={full?null:'/facilities'} linkText="View all facilities">Facilities to support your care, close to home.</SectionTitle><div className="facility-grid">{facilities.slice(0,full?9:6).map(f=><div className="facility-item" key={f.name}><span className="icon-box"><Icon name={f.icon}/></span><div><h3>{f.name}</h3><p>{f.description}</p></div></div>)}</div><div className="facility-highlight"><Icon name="ShieldPlus" size={25}/><div><strong>ICU, Oxygen, Nebulization &amp; Physiotherapy Facilities Available</strong><span><span lang="hi">खतना एवं हिजामा की सुविधा उपलब्ध है</span><span className="khitan-english">Khitan and Hijama services available.</span></span></div><a href={`tel:${clinicInfo.phones[0]}`} aria-label="Call to enquire about facilities"><Icon name="ArrowUpRight"/></a></div></div></section>;}
export function DoctorSpotlight(){const doctor=doctors[0];return <section className="spotlight-section"><div className="container spotlight-grid"><div className="spotlight-photo"><DoctorPhoto/><div className="spotlight-photo-label"><Icon name="Stethoscope"/><span>Personal attention.<br/><strong>Thoughtful care.</strong></span></div></div><div className="spotlight-copy"><span className="eyebrow">MEET YOUR DOCTOR</span><h2>{doctor.name}</h2><p className="spotlight-specialty">{doctor.specialty}</p><div className="qualification-list">{doctor.qualifications.map(q=><span key={q}><Icon name="BadgeCheck" size={18}/>{q}</span>)}</div><p>From routine checkups to your next health concern, start a conversation about your care. Contact our team to arrange a consultation with Dr. Rizwan.</p><div className="button-row"><Button to={`/appointment?doctor=${encodeURIComponent(doctor.name)}`}>Book Appointment<Icon name="ArrowUpRight" size={17}/></Button><Button outline href={`tel:${clinicInfo.phones[0]}`}><Icon name="Phone" size={16}/>Call for Consultation</Button></div><ExternalLink className="text-link" href={createWhatsAppURL(`Hello Hayat Health Care Clinic, I would like to enquire about a consultation with ${doctor.name}.`)}><Icon name="MessageCircle" size={17}/>Connect on WhatsApp</ExternalLink></div></div></section>;}
export function DoctorsPreview(){return <section className="section container"><SectionTitle eyebrow="PEOPLE BEHIND YOUR CARE" title="Meet our doctors" link="/doctors" linkText="Meet the full team"/><div className="doctors-grid">{doctors.slice(1,4).map(d=><DoctorCard doctor={d} key={d.id}/>)}</div><p className="section-note">Please contact the clinic to confirm doctor availability before your visit.</p></section>;}
const reasons=[['HeartHandshake','Patient-focused approach','Care starts with understanding your concerns.'],['Hospital','Essential healthcare facilities','Consultations, diagnostics and support in one place.'],['Stethoscope','Multiple specialities','A team covering a range of healthcare needs.'],['HeartPulse','Emergency support','Reach our clinic team directly, 24/7.'],['MapPin','Convenient location','Near Bazaar Samiti on Sitamarhi Road, Pupri.'],['MessageCircle','Easy WhatsApp appointments','Request a visit in just a few simple steps.']];
export function WhyChooseUs(){return <section className="section pale-section"><div className="container"><SectionTitle eyebrow="A LITTLE MORE CARE" title="Why choose Hayat Health Care Clinic?">A familiar place to turn to, whenever your family needs care.</SectionTitle><div className="why-grid">{reasons.map(([i,n,d])=><div className="why-item" key={n}><Icon name={i} size={25}/><h3>{n}</h3><p>{d}</p></div>)}</div></div></section>;}
export function EmergencyCTA(){return <section className="container emergency-section"><div className="emergency-banner"><span className="emergency-badge"><Icon name="Siren" size={36}/></span><div><span className="eyebrow">24/7 EMERGENCY SUPPORT</span><h2>Need immediate medical assistance?</h2><p>Our clinic provides emergency support. Contact us immediately for assistance.</p></div><div className="emergency-numbers">{clinicInfo.phones.map(p=><a href={`tel:${p}`} key={p}><Icon name="Phone" size={17}/>Call {p}</a>)}</div></div></section>;}
export function FAQ(){return <section className="section container faq-section"><div><span className="eyebrow">A FEW HELPFUL ANSWERS</span><h2>Questions?<br/>We’re here to help.</h2><p>Planning your visit should feel simple. Here are a few things you might like to know.</p><ExternalLink className="text-link" href={createWhatsAppURL()}>Ask our team<Icon name="ArrowUpRight" size={16}/></ExternalLink></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Icon name="Plus" size={17}/></summary><p>{a}</p></details>)}</div></section>;}
export function LocationSection(){return <section className="section pale-section"><div className="container location-grid"><div><span className="eyebrow">FIND US IN YOUR NEIGHBOURHOOD</span><h2>Your care is<br/>closer than you think.</h2><p>{clinicInfo.address}</p><p className="hindi-address" lang="hi">{clinicInfo.hindiAddress}</p><Button href={mapsURL} target="_blank" rel="noopener noreferrer"><Icon name="MapPin" size={17}/>Open in Google Maps<Icon name="ArrowUpRight" size={16}/></Button><p className="map-note">Maps shows an address search. Call us if you need help finding the clinic.</p></div><iframe title="Google Maps address search for Hayat Health Care Clinic, Pupri" src={`https://maps.google.com/maps?q=${encodeURIComponent(mapQuery)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></section>;}
export function HealthCTA(){return <section className="health-cta container"><div><span className="eyebrow">LET’S TAKE THE NEXT STEP, TOGETHER</span><h2>Your health deserves timely care.</h2><p>Speak with our clinic team to learn about doctor availability and services.</p></div><div className="button-row"><Button to="/appointment">Book Appointment<Icon name="ArrowUpRight" size={17}/></Button><Button outline href={`tel:${clinicInfo.phones[0]}`}><Icon name="Phone" size={17}/>Call Clinic</Button></div></section>;}
