import { useEffect,useRef,useState } from 'react';
import { Icon,SectionTitle } from './UI';
import clinicBanner from '../../assets/clinic/clinic-banner.webp';
import servicesPoster from '../../assets/clinic/services-poster.webp';
import teamBanner from '../../assets/clinic/team-banner.webp';
import doctorPoster from '../../assets/clinic/doctor-rizwan-reference.webp';
const pictures=[{src:doctorPoster,label:'Dr. Md. Rizwan — clinic information'},{src:teamBanner,label:'Meet the clinic’s medical team'},{src:servicesPoster,label:'Healthcare services — Hindi'},{src:clinicBanner,label:'Hayat clinic services and contact details'}];
export default function Gallery(){const [index,setIndex]=useState(null);const dialog=useRef();const trigger=useRef();const active=index!==null;useEffect(()=>{if(active){dialog.current.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;};}else if(dialog.current.open){dialog.current.close();trigger.current?.focus();}},[active]);const close=()=>setIndex(null);return <section className="section pale-section"><div className="container"><SectionTitle eyebrow="A WINDOW INTO OUR CLINIC" title="Clinic gallery">Explore the clinic’s original information and service posters.</SectionTitle><div className="gallery-grid">{pictures.map((p,i)=><button key={p.src} className="gallery-card" aria-label={`View ${p.label}`} onClick={e=>{trigger.current=e.currentTarget;setIndex(i);}}><img src={p.src} alt={p.label} loading="lazy" width="400" height="300"/><span>{p.label}<Icon name="Expand" size={17}/></span></button>)}</div></div><dialog ref={dialog} className="gallery-dialog" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}} onKeyDown={e=>{if(e.key==='ArrowRight')setIndex(i=>(i+1)%pictures.length);if(e.key==='ArrowLeft')setIndex(i=>(i+pictures.length-1)%pictures.length);}} aria-labelledby="gallery-caption">{active&&<div className="lightbox-content"><button className="lightbox-close" aria-label="Close gallery" onClick={close}><Icon name="X"/></button><img src={pictures[index].src} alt={pictures[index].label}/><div className="lightbox-bottom"><button aria-label="Previous image" onClick={()=>setIndex((index+pictures.length-1)%pictures.length)}><Icon name="ChevronLeft"/></button><p id="gallery-caption" aria-live="polite">{pictures[index].label} <span>{index+1} / {pictures.length}</span></p><button aria-label="Next image" onClick={()=>setIndex((index+1)%pictures.length)}><Icon name="ChevronRight"/></button></div></div>}</dialog></section>;}

