import { useEffect, useId, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { services } from '../../data/services';
import { doctors } from '../../data/doctors';
import { appointmentMessage, contactMessage, createWhatsAppURL, todayInIndia, validateRequest } from '../../utils/whatsapp';
import { Icon } from './UI';
const empty = { name:'', phone:'', age:'', gender:'', service:'', doctor:'', date:'', time:'', message:'', email:'', subject:'', consent:false };
export default function RequestForm({ appointment = true }) {
  const [params] = useSearchParams(); const [values,setValues]=useState(()=>({...empty, doctor:doctors.some(d=>d.name===params.get('doctor'))?params.get('doctor'):'', service:services.some(s=>s.name===params.get('service'))?params.get('service'):''}));
  const [errors,setErrors]=useState({});const [requestURL,setRequestURL]=useState('');const id=useId();const formRef=useRef();
  useEffect(()=>{if(!appointment||!document.modelContext?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'prepare_appointment_request',title:'Prepare appointment request',description:'Select a service and optional doctor in the visible appointment form. Does not send a message or confirm an appointment. The visitor completes and submits the request.',inputSchema:{type:'object',properties:{service:{type:'string',enum:services.map(s=>s.name)},doctor:{type:'string',enum:doctors.map(d=>d.name)}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||!services.some(s=>s.name===input.service)||(input.doctor&&!doctors.some(d=>d.name===input.doctor)))throw new Error('Choose a listed service and doctor.');setValues(v=>({...v,service:input.service,doctor:input.doctor||''}));setRequestURL('');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));formRef.current?.scrollIntoView({block:'center'});return{status:'prepared',service:input.service,doctor:input.doctor||'Any available doctor',sent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional progressive enhancement. */}return()=>lifecycle.abort();},[appointment]);
  const change=e=>{const {name,value,type,checked}=e.target;setValues(v=>({...v,[name]:type==='checkbox'?checked:value}));setErrors(v=>({...v,[name]:undefined}));setRequestURL('');};
  const submit=e=>{e.preventDefault();const nextErrors=validateRequest(values,appointment);if(appointment&&values.service&&!services.some(s=>s.name===values.service))nextErrors.service='Choose a listed service.';setErrors(nextErrors);if(Object.keys(nextErrors).length){formRef.current.elements.namedItem(Object.keys(nextErrors)[0])?.focus();return;}const url=createWhatsAppURL(appointment?appointmentMessage(values):contactMessage(values));setRequestURL(url);window.open(url,'_blank','noopener,noreferrer');};
  const field=(name,label,options={})=>{const {type='text',required=false,choices,span,helper,...rest}=options;return <div className={`form-field ${span?'field-full':''}`} key={name}><label htmlFor={`${id}-${name}`}>{label}{required&&<span aria-hidden="true"> *</span>}</label>{choices?<select id={`${id}-${name}`} name={name} value={values[name]} onChange={change} required={required} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${id}-${name}-error`:undefined}><option value="">{rest.placeholder||'Please select'}</option>{choices.map(c=><option value={c} key={c}>{c}</option>)}</select>:type==='textarea'?<textarea id={`${id}-${name}`} name={name} rows={3} value={values[name]} onChange={change} maxLength={500} required={required} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${id}-${name}-error`:`${id}-${name}-help`}/>:<input id={`${id}-${name}`} type={type} name={name} value={values[name]} onChange={change} required={required} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name]?`${id}-${name}-error`:helper?`${id}-${name}-help`:undefined} {...rest}/>} {helper&&<small id={`${id}-${name}-help`}>{helper}</small>}{errors[name]&&<small className="field-error" id={`${id}-${name}-error`}>{errors[name]}</small>}</div>;};
  return <form ref={formRef} className="request-form" onSubmit={submit} noValidate><div className="form-heading"><span className="icon-box"><Icon name={appointment?'CalendarDays':'MessageCircle'}/></span><div><h3>{appointment?'Request your appointment':'Send us a message'}</h3><p>Fields marked * are required.</p></div></div><div className="form-grid">
    {field('name',appointment?'Patient Name':'Name',{required:true,autoComplete:'name',maxLength:80,placeholder:'Your full name'})}
    {field('phone','Phone Number',{type:'tel',required:true,autoComplete:'tel',inputMode:'tel',maxLength:18,placeholder:'10-digit mobile number'})}
    {appointment?<>{field('age','Age',{type:'number',min:0,max:120,inputMode:'numeric',placeholder:'Optional'})}{field('gender','Gender',{choices:['Female','Male','Other','Prefer not to say'],placeholder:'Optional'})}{field('service','Select Service',{required:true,choices:services.map(s=>s.name),placeholder:'Choose a service'})}{field('doctor','Select Doctor',{choices:doctors.map(d=>d.name),placeholder:'Any available doctor'})}{field('date','Preferred Date',{type:'date',required:true,min:todayInIndia()})}{field('time','Preferred Time',{type:'time',required:true,helper:'Indian Standard Time (IST). Subject to availability.'})}</>:<>{field('email','Email',{type:'email',autoComplete:'email',maxLength:120,placeholder:'Optional'})}{field('subject','Subject',{required:true,maxLength:120,placeholder:'How can we help?'})}</>}
    {field('message',appointment?'Message / Symptoms':'Message',{type:'textarea',span:true,required:!appointment,helper:'Keep it brief. Please do not include detailed medical history or sensitive documents.'})}
  </div>{appointment&&<div className="consent-field"><label><input name="consent" type="checkbox" checked={values.consent} onChange={change} required aria-invalid={Boolean(errors.consent)} aria-describedby={errors.consent?`${id}-consent-error`:undefined}/><span>I understand this is an appointment request and requires confirmation.</span></label>{errors.consent&&<small className="field-error" id={`${id}-consent-error`}>{errors.consent}</small>}</div>}<button type="submit" className="button form-submit"><Icon name="MessageCircle" size={18}/>{appointment?'Request Appointment via WhatsApp':'Continue to WhatsApp'}<Icon name="ArrowUpRight" size={17}/></button><p className="form-privacy"><Icon name="LockKeyhole" size={12}/>Your details open in WhatsApp for you to review and send. <Link to="/privacy-policy">Privacy policy</Link></p>{requestURL&&<div className="form-success" role="status"><Icon name="CircleCheck" size={22}/><div><strong>{appointment?'Your request is ready':'Your message is ready'}</strong><p>{appointment?'Your appointment request will be sent to the clinic via WhatsApp. The clinic will confirm availability.':'Review and send your message in WhatsApp. The clinic can then respond to your enquiry.'}</p><a href={requestURL} target="_blank" rel="noopener noreferrer">Open WhatsApp again <Icon name="ArrowUpRight" size={14}/></a></div></div>}</form>;
}
