import { Link } from 'react-router-dom';
import { Activity, ArrowUp, ArrowUpRight, Baby, BadgeCheck, Bone, CalendarDays, ChevronLeft, ChevronRight, CircleCheck, Cloud, Droplets, Expand, HeartHandshake, HeartPulse, Hospital, LockKeyhole, MapPin, Menu, MessageCircle, Microscope, Monitor, Phone, Pill, Plus, Scissors, Search, ShieldCheck, ShieldPlus, Siren, Smile, Sparkles, Stethoscope, UserRound, Wind, X } from 'lucide-react';
const Icons = { Activity, ArrowUp, ArrowUpRight, Baby, BadgeCheck, Bone, CalendarDays, ChevronLeft, ChevronRight, CircleCheck, Cloud, Droplets, Expand, HeartHandshake, HeartPulse, Hospital, LockKeyhole, MapPin, Menu, MessageCircle, Microscope, Monitor, Phone, Pill, Plus, Scissors, Search, ShieldCheck, ShieldPlus, Siren, Smile, Sparkles, Stethoscope, UserRound, Wind, X };
import { motion } from 'framer-motion';
import doctorPoster from '../../assets/clinic/doctor-rizwan-reference.webp';
export function Icon({ name, size = 22, ...props }) { const Component = Icons[name] || Icons.HeartPulse; return <Component size={size} aria-hidden="true" {...props}/>; }
export function Button({ to, href, children, outline, className = '', ...props }) { const classes=`button ${outline ? 'button-outline' : ''} ${className}`; return to ? <Link className={classes} to={to} {...props}>{children}</Link> : <a className={classes} href={href} {...props}>{children}</a>; }
export function ExternalLink({ children, ...props }) { return <a target="_blank" rel="noopener noreferrer" {...props}>{children}</a>; }
export function SectionTitle({ eyebrow, title, children, link, linkText }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{link ? <Link className="text-link" to={link}>{linkText}<Icon name="ArrowUpRight" size={17}/></Link> : children && <p>{children}</p>}</div>; }
export function PageHeader({ eyebrow, title, children }) { return <section className="page-header"><div className="container"><div className="breadcrumb"><Link to="/">Home</Link><Icon name="ChevronRight" size={12}/><span>{eyebrow}</span></div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{children}</p></div></section>; }
export function Reveal({ children, className = '' }) { return <motion.div className={className} initial={{ opacity:0, y:12 }} whileInView={{ opacity:1, y:0 }} viewport={{ once:true, amount:0.06 }} transition={{ duration:0.4 }}>{children}</motion.div>; }
export function DoctorPhoto({ className = '', eager = false }) { return <div className={`doctor-crop ${className}`}><img src={doctorPoster} alt="Dr. Md. Rizwan, General Physician and Surgeon at Hayat Health Care Clinic" loading={eager ? 'eager' : 'lazy'} fetchPriority={eager ? 'high' : 'auto'} width="1122" height="1402"/></div>; }
export function Brand() { return <Link to="/" className="brand" aria-label="Hayat Health Care Clinic home"><span className="brand-icon"><Icon name="HeartPulse"/></span><span><strong>HAYAT</strong><b>HEALTH CARE CLINIC</b><small lang="hi">हयात हेल्थ केयर क्लिनिक</small></span></Link>; }

